# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20160726_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='pusrchase_protection',
            new_name='purchase_protection',
        ),
    ]
